exports.cookie = facebookCookie = [
  {
    domain: ".facebook.com",
    expirationDate: 1735215605.21626,
    hostOnly: false,
    httpOnly: true,
    key: "datr",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value: "8_FdZcC35dgIznOBDLIJZBaO",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1710619803.681225,
    hostOnly: false,
    httpOnly: true,
    key: "fr",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value:
      "13fqE8HFmYl2jKLm7.AWXjGO0pRQAQ56tqtTcxPHZUya4.Blf1Sk.Sq.AAA.0.0.Blf1Wf.AWWWBTKbHm0",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1734379553.208593,
    hostOnly: false,
    httpOnly: true,
    key: "xs",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value:
      "49%3AUaSFhK_g4jOrIA%3A2%3A1701207036%3A-1%3A3325%3A%3AAcU3suzVapQMt6Lkd5LAiB_gTNcLo8j59q77ntbACFA",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1734379553.208534,
    hostOnly: false,
    httpOnly: false,
    key: "c_user",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value: "100089486186582",
  },
  {
    domain: ".facebook.com",
    hostOnly: false,
    httpOnly: false,
    key: "presence",
    path: "/",
    sameSite: null,
    secure: true,
    session: true,
    storeId: null,
    value:
      "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1702843807026%2C%22v%22%3A1%7D",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1703448605,
    hostOnly: false,
    httpOnly: false,
    key: "dpr",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value: "1.25",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1735767039.994347,
    hostOnly: false,
    httpOnly: true,
    key: "sb",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: null,
    value: "CTWXZGwHJ7f0rwFnfdNS7CKG",
  },
  {
    domain: ".facebook.com",
    expirationDate: 1703448605,
    hostOnly: false,
    httpOnly: false,
    key: "wd",
    path: "/",
    sameSite: "lax",
    secure: true,
    session: false,
    storeId: null,
    value: "1536x730",
  },
];
